config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/users/:id', to: 'users#show'

  root 'index#home'

  get 'thegame' => 'index#game'

  get 'about_me' => 'index#aboutme'

  get 'community' => 'posts#community'

  post 'set_avatar' => 'index#set_avatar'

  resources :posts

  resources :scores, :only => [:create]

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

end

app/models/score.rb
class Score < ActiveRecord::Base
	belongs_to :user

	validates :kills, presence: true
	validates :chronotime, presence: true
	validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true

  has_many :posts
  validates_associated :posts
  has_many :scores
  validates_associated :scores

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
	end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

	def home
		render 'home'
	end

	def game
		@score = Score.new
		@scores = Score.order('kills desc')
		render 'game'
	end

	def aboutme
		render 'aboutme'
	end

	def set_avatar
		if current_user
			current_user.avatar = avatar_params[:avatar_selected]
			current_user.save
		end
		redirect_to :back
	end

	private

    def avatar_params
      params.require(:user).permit(:avatar_selected)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def community

		@post = Post.new

		@posts = Post.all
		render 'community'
	end

	def create
		@post = Post.new(post_params)
		@post.user = current_user

      	if @post.save
          redirect_to community_path, notice: 'Post was successfully created.'
      	else
      	  @posts = Post.all
          render 'community'
      	end
	end


	private

    def post_params
      params.require(:post).permit(:title, :comment)
    end

end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController

	def create

			@score = Score.new(score_params)
			@score.user = current_user

      if @score.save
        redirect_to thegame_path, notice: 'Score shared!'
      else
      	# @scores = score.all
        redirect_to thegame_path
      end

	end

	private

    def score_params
      params.require(:score).permit(:kills, :chronotime)
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: :show
  def show
	@user = User.find(params[:id])
	render 'users/show'
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/aboutme.html.erb
<!-- ****************** DECORATION ****************** -->
<div class="building-1">
	<img src="assets/misc/building-1.png">
</div>
<div class="tree">
	<img src="assets/misc/tree.png">
</div>

<!-- ****************** ABOUT ME ****************** -->


<div class="about-section">

	<img src="assets/misc/me2.jpg" class="about-img">

	<div class="about-contact_info-section">
		<h3 class="about-info-title">Contact Information</h3>
		<br/>
		<h5 class="name_email_link_git">Name:</h5>
		<p class="contact_info">Sergio Silva Rubio</p>
		<br/>
		<h5 class="name_email_link_git">E-mail:</h5>
		<p class="contact_info">sertykos@gmail.com</p>
		<!-- Icon to send me an e-mail -->
		<br/>
		<h5 class="name_email_link_git">Linkedin:</h5>
		<p class="contact_info"><a href="https://www.linkedin.com/profile/view?id=228948048&trk=nav_responsive_tab_profile" class="contact-links">es.linkedin.com/in/sergiosilvarubio/</a></p>
		<br/>
		<h5 class="name_email_link_git">Github:</h5>
		<p class="contact_info"><a href="https://github.com/sertykos" class="contact-links">https://github.com/sertykos</a></p>
	</div>

	<div class="about-extra_info-section">
		<h3 class="about-info-title">Know me better!</h3>
		<ul class="about-extra_info-ul">
			<li class="about-extra_info-birth">
				<h5 class="about-extra_info-h5">Birth: </h5>
				<p class="about-extra_info-p">July 1991</p>
			</li>
			<li class="about-extra_info-interests">
				<h5 class="about-extra_info-h5">Interests: </h5>
				<ul>
					<li><p class="interest_main-txt">Programming</p> (Software and Web Development)</li>
					<li><p class="interest_main-txt">Videogames</p> (Rol, MMORPG, RPG, Online...)</li>
					<li class="parties-li">Parties with friend and NEW friends!</li>
					<li><p class="interest_main-txt">Movies & TV-series</p> (Walking Dead, South Park, The Simpsons, Futurama...)</li>
				</ul>
			</li>
			<li>
				<h5 class="about-extra_info-h5">Languages: </h5>
				<p class="about-extra_info-p">Spanish ; English</p>
			</li>
		</ul>
	</div>

</div>

app/views/index/game.html.erb
<div class="background-game"></div>

<div class="liana-left">
	<img src="assets/misc/liana_double_1.png" class="liana-left-1">
	<img src="assets/misc/liana_double_1.png" class="liana-left-2">
	<img src="assets/misc/liana_double_2.png" class="liana-left-3">
	<img src="assets/misc/liana_double_1.png" class="liana-left-4">
	<img src="assets/misc/liana_double_2.png" class="liana-left-5">
	<img src="assets/misc/liana_double_end.png" class="liana-left-6-end">
</div>

<div  class="liana-right">
	<img src="assets/misc/liana-right-1.png" class="liana-right-1">
	<img src="assets/misc/liana-right-2.png" class="liana-right-2">
	<img src="assets/misc/liana-right-1.png" class="liana-right-3">
	<img src="assets/misc/liana-right-2.png" class="liana-right-4">
	<img src="assets/misc/liana-right-2.png" class="liana-right-5">
	<img src="assets/misc/liana-right-1.png" class="liana-right-6">
	<img src="assets/misc/liana-right-2.png" class="liana-right-7">
	<img src="assets/misc/liana-right-1.png" class="liana-right-8">
	<img src="assets/misc/liana-right-end.png" class="liana-right-9-end">
</div>

<img src="assets/misc/blood.png" class="blood-img">
<p class="game-title">Play & Share</p>

<div class="leaderboard-section">
	<h3 class="leaderboard-title">Leaderboard</h3>
	<p class="kills_time_name">Kills - Time - Name</p>
	<% @scores.each do |score| %>

		<div class="user-game_info">
			<p class="user-game_kills"><%= score.kills %></p>
			<p class="user-game_chronotime"><%= score.chronotime %></p>
			<p class="user-game_name"><%= score.user.name %></p>
			<p class="user-game_created"><%= score.created_at %></p>
		</div>

	<% end %>
</div>

<div id="mask_start" class="mask_start">
	<img src="assets/game/mage.png" class="game-start-mage">
	<p class="game-start">Mage Defense</p>
	<img src="assets/game/monster.png" class="game-start-monster">
	<img src="assets/game/fire-bg.png" class="game-start-fire">
	<p class="press-start cssanimations">-- Press START --</p>
</div>
<div id="mask_stop" class="mask_stop">
	<p class="share-txt">Share your time and kills with the community!</p>
</div>
<script src="assets/game.js"></script>

<div class="chrono">

	<form name="chronoForm">
    	<input class="start-btn buttons" type="button" name="startstop" value="START" onClick="chronoStart()"><!--<img src="/assets/textures/magic-btn.png">--></input>
    	<input id="reset-btn" class="reset-btn buttons" type="button" name="reset" value="Reset!" onClick="chronoReset()" />
	</form>
	<span id="chronotime" class="chronotime">0:00:00:00</span>

<% if user_signed_in? %>

	<%= form_for @score do |f| %>

		<%= f.hidden_field :kills, id: 'kills-field' %>
		<%= f.hidden_field :chronotime, id: 'chronotime-field' %>
		<%= f.submit "Share", class: 'game-share-btn' %>

	<% end %>

<% else %>

	<h2>To share your score sign in <a href="#">here</a>.</h2>
	<p>If you have no yet signed up, I invite you to do it! <a href="#">Sign up</a></p>

<% end %>

	<!--<input type="submit" value="Share" class="share-btn" />-->

</div>

app/views/index/home.html.erb
<!-- ********************* Main body part ********************* -->

<div class="background-div">

  <div class="news">
    <img src="assets/misc/welcome.png" class="img-new">
    <div class="new-by">
      <h5 class="by-txt">New by:</h5>
      <p class="admin-txt">Administrator</p>
    </div>
    <article class="new-art">
      <p class="new-p">
        I am more than happy to welcome everyone to Play&Share !<br/><br/>
        If you love videogames then this website is perfect for you. You will have the feeling of
        playing a 2D videogame while you are surfering through it.
        I am aware that all the people here doesn´t like just "the feeling of playing" but what all
        you guys want is "PLAY". Ok! take it easy...get confortable y go to "The Game" to see what´s really going on ! ! !
      </p>
    </article>
  </div>

  <div class="news">
    <img src="assets/misc/patch.jpg" class="img-new">
    <div class="new-by">
      <h5 class="by-txt">New by:</h5>
      <p class="admin-txt">Administrator</p>
    </div>
    <article class="new-art">
      <p class="new-p">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet architecto dolore ab deserunt cumque veritatis voluptatem pariatur quisquam provident, quis quibusdam impedit neque fugiat sunt dignissimos autem. Delectus, sequi. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, molestiae et id, animi eveniet a quos incidunt perspiciatis, impedit quas sed. Vel, aut repellendus! Quos atque accusamus blanditiis adipisci quibusdam.
      </p>
    </article>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" type="image/x-icon" href="assets/misc/orb.ico" />
  <title>Play&Share</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Indie+Flower' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Special+Elite' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Griffy' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>


<!-- Header -->

<header id="header" class="header">

  <div class="background-header"></div>

  <div class="logo">
    <img src="assets/misc/leaf.png" class="leaf">
    <img src="assets/misc/wasd.png" class="wasd">
    <h1 class="logo_play_share">Play</h1>
    <h2 class="logo_and">&</h2>
    <h1 class="logo_play_share">Share</h1>
  </div>

<!-- Sign Up/In -->

  <% if user_signed_in? %>

    <div class="sign-section">
      <p class="sign-title">Welcome <%= current_user.name %> !</p>
      <%= image_tag current_user.avatar, id: "user-avatar", class: "user-avatar", onclick: "toggle_visibility()" %>
      <p class="sign_out-txt" >Sign Out</p>
      <%= link_to image_tag("misc/block-sign_out.png"), destroy_user_session_path, method: 'DELETE', class: "sign_out-btn" %>
    </div>

  <% else %>

    <div class="sign-section">
      <p class="sign-title">Have fun with us!</p>
      <p class="sign_in-txt">Sign In</p>
      <%= link_to image_tag("misc/block-sign_in.png"), new_user_session_path, :method => "get", class: "sign_in-btn" %>
      <p class="sign_up-txt">Sign Up</p>
      <%= link_to image_tag("misc/block-sign_up.png"), new_user_registration_path, :method => "get", class: "sign_up-btn" %>
    </div>

  <% end %>

  <div id="avatar-select" class="avatar-select">

    <% (1..10).each do |i| %>
      <%= link_to image_tag("avatar/avatar-#{i}.jpeg", class: "avatar_to_choose"), set_avatar_path(:user => {:avatar_selected => "avatar/avatar-#{i}.jpeg"}), method: :post %>
    <% end %>

  </div>

</header>

<!-- ********************* Navigation Bar ********************* -->

<div id="dec-nav" class="dec-nav-bar">
  <img src="assets/textures/up-left-texture.png" class="top-dec-nav-bar top-left-end-1">
  <img src="assets/textures/up-left-texture.png" class="top-dec-nav-bar top-left-end-2">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-1">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-2">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-3">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-4">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-5">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-6">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-7">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-8">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-9">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-10">
  <img src="assets/textures/top-nav-texture.png" class="top-dec-nav-bar top-11">
  <img src="assets/textures/up-right-texture.png" class="top-dec-nav-bar top-right-end-2">
  <img src="assets/textures/up-right-texture.png" class="top-dec-nav-bar top-right-end-1">
  <img src="assets/textures/main-nav-texture.png" class="top-dec-nav-bar main-left-1">
  <img src="assets/textures/main-nav-texture.png" class="top-dec-nav-bar main-right-1">
  <div class="bottom-dec-nav-bar">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-1">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-2">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-3">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-4">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-5">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-6">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-7">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-8">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-9">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-10">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-11">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-12">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-13">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-14">
    <img src="assets/textures/main-nav-texture.png" class="bottom-texture-15">
  </div>
  <div class="bottom-end-dec-nav-bar">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-1">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-2">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-3">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-4">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-5">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-6">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-7">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-8">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-9">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-10">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-11">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-12">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-13">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-14">
    <img src="assets/textures/bottom-end-texture-1.png" class="bottom-end-texture-15">
    <img src="assets/textures/bottom-end-texture-2.png" class="bottom-end-texture-16">
  </div>
  <div class="cracks-dec-nav">
    <img src="assets/textures/crack.png" class="crack-1">
    <img src="assets/textures/crack.png" class="crack-2">
    <img src="assets/textures/crack.png" class="crack-3">
    <img src="assets/textures/crack.png" class="crack-4">
    <img src="assets/textures/crack.png" class="crack-5">
    <img src="assets/textures/crack.png" class="crack-6">
    <img src="assets/textures/crack.png" class="crack-7">
    <img src="assets/textures/crack.png" class="crack-8">
  </div>
</div>

<nav id="nav" class="nav-bar">
  <ul class="ul-nav-bar">
    <li class="li-nav-bar li-1">
        <%= link_to "Home", root_path, :method => "get", class: "a-link-nav-bar" %>
    </li>
    <li class="li-nav-bar li-2">
        <%= link_to "The Game", thegame_path, :method => "get", class: "a-link-nav-bar" %>
    </li>
    <li class="li-nav-bar li-3">
        <%= link_to "About me", about_me_path, :method => "get", class: "a-link-nav-bar" %>
    </li>
    <li class="li-nav-bar li-4">
        <%= link_to "Community", community_path, :method => "get", class: "a-link-nav-bar" %>
    </li>
  </ul>
</nav>

<%= yield %>

<!-- ********************* Footer ********************* -->

<footer id="footer" class="footer">

  <p class="copyright">©SergioSR<p>

</footer>

</body>
</html>

app/views/posts/community.html.erb
<div class="background-community"></div>

<h2 class="community-title">Welcome to the Community</h2>

<div class="community-new_post-section">

<% if user_signed_in? %>

	<%= form_for @post do |f| %>

		<div class="new_post-inputs">
		<%= f.label :title, class: 'community-title_label' %>
		<%= f.text_field :title, class: 'community-title_input' %>
		<br/>
		<%= f.label :comment, class: 'community-comment_label'%>
		<%= f.text_area :comment, size: "24x6", class: 'community-comment_input' %>
		</div>
		<br/>
		<%= f.submit "Post", class: 'community-new_post-btn' %>

	<% end %>

<% else %>

	<h2 class="community-sign">To comment sign in <a href="/users/sign_in">here</a>.</h2>
	<p class="community-sign community-sign_up">If you have no yet signed up, I invite you to do it! <a href="/users/sign_up">Sign up</a></p>

<% end %>

</div>

<table class="community-table_posts">

  <tbody class="community-table_body">
    <% @posts.each do |post| %>
      <tr  class="community-table-tr">
      	<!--<td class="community-table_img"><img src="assets/misc/book.png"></td>-->
      	<td class="community-table_avatar"><%= image_tag post.user.avatar %></td>
        <td class="community-table_title-txt"><%= post.title %></td>
        <td class="community-table_comment-txt"><%= post.comment %></td>
      	<td class="community-table_by-txt"><p>By: <%= post.user.name %></p></td>
      	<td class="community-table_date-txt"><%= post.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/show.html.erb
<% if user_signed_in? %>

	<h2>Welcome <%= current_user.name %>!</h2>
	<%= link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>

<% else %>

	<h2>Nobody logued in</h2>

<% end %>